webserver:
  image: zrrrzzt/app-tfk-politikere
  ports:
    - "80:80"
  environment:
    SERVER_PORT: 80
    API_URL: http://127.0.0.1:3000
  links:
   - apiserver
apiserver:
  build: .
  name:
    api-tfk-politikere
  links:
    - mongodb
  ports:
    - "3000:3000"
mongodb:
  image: mongo
  ports:
   - "27017:27017"